name: Automated API tests using Postman CLI

on: push

jobs:
  clean-and-seed-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install && npm run seed
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "23726650-cae241ae-91ba-4d83-8204-a7a514125923" -e "23726650-5eb2cd25-452b-46bd-a639-47051d198e75"